{ label: 'Asal Surat',                          class: 'hidden md:table-cell' },
                                        { label: 'Waktu',                               class: 'hidden md:table-cell' },
                                        { label: 'Perihal',                             class: 'hidden md:table-cell' },
                                        { label: 'Link Surat',                          class: 'hidden md:table-cell' },
                                        { label: 'Disposisi',                           class: 'hidden md:table-cell' },
                                        { label: 'Catatan',                             class: 'hidden md:table-cell' },
                                        { label: 'Surat Tugas',                         class: 'hidden md:table-cell' },
                                        { label: 'Catatan Internal',                    class: 'hidden lg:table-cell' },
                                        { label: 'Laporan / Materi Presentasi',         class: 'hidden lg:table-cell' },