services:

  app:
    build: .
    container_name: laravel_app

    working_dir: /app

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:16

    container_name: laravel_postgres

    environment:
      POSTGRES_DB: arsip_djprl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    ports:
      - "5432:5432"
